---
- name: Upload cert content
  loop: "{{ certify_default_certs + certify_extra_certs }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Reload services
  ansible.builtin.copy:
    content: "{{ item.crt }}"
    dest: "/etc/ssl/certs/{{ item.name }}.crt"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('u=rw,g=r,o=r') }}"
  tags:
    - certify

- name: Upload key content
  loop: "{{ certify_default_certs + certify_extra_certs }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Reload services
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/etc/ssl/private/{{ item.name }}.key"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('u=rw,g=r,o=r') }}"
  tags:
    - certify

...
